/* JDBC Query Application
 * created for CSCI 112 Summer 2015
 * last edited August 17, 2015 by Jefferson Zhumi
 * @author Jefferson

 * This code connects to a remote MYSQL database on the website CWHerbert.com
 * It connects via a fixed IP address (IPv4) to the database CWHDemo and
 * the table "fall2014"
 *
 * The queryCSV method will read and write the query from the table "fall2014"
 * to a CSV file. 
 * 
 * The second method will 
 *
 * host IP address: 68.178.216.151
 * database:        CWHDemo
 * username:        student
 * password:        Student%123  (Note capital "S" in password, but not in username.)
 
 */

/* The class for the JDBC communications driver for MySQL must be available.
 * It can be included in a locally asccessible library, 
 * by using the import statement    import com.mysql.jdbc.Driver;
 * or by using the Class.forName(com.mysql.jdbc.Driver) within your code 
 */
package jdbc;

import java.sql.*;
import java.io.*;

public class JDBC {

    /**
     * The main method will print a description of the program 
     * It will set a the query connection to the database "fall 2014"
     * then, it will call the methods queryCSV() and queryDesign()
     */
    public static void main(String[] args) throws Exception {
        System.out.println("Welcome!");
        System.out.println("The application will send fall2014 query to a CSV File.");
        System.out.println("It will also print a self generated question query." + "\n");

        // Connect to a database by establishing a Connection object
        Connection conn = DriverManager.getConnection("jdbc:mysql://68.178.216.151/CWHDemo", "student", "Student%123");
        Statement st = conn.createStatement();

        //call method to query database and write result set to CSV file
        queryCSV(st);

        //call method to query database to asnwer the question generated by the user 
        queryDesign(st);

        // close connection to database
        conn.close();

    } // end main
/* The following method performs an SQL query
     * The parameter must be a Statement object with an established connection
     * to an SQL database.
     * In addition, it also sends the query to a CSV File
     */

    public static void queryCSV(Statement s) throws Exception {
        System.out.println("*******************************************************");
        System.out.println(" Fall 2014 query to CSV sent.");
        System.out.println("*******************************************************");

        String queryString; // a String to hold an SQL query 
        ResultSet rs;       // the result set from an SQL query as a table

        // create a File class object and give the file the name SQLresult.txt
        java.io.File sqlResult = new java.io.File("SQLresult.csv");

        // Create a PrintWriter text output stream and link it to the File sqlResult
        java.io.PrintWriter outfile = new java.io.PrintWriter(sqlResult);

        // Create an SQL query as as String for this statement
        // this query returns all rows and all columns from the database 
        queryString = "SELECT crn, subject, course, section, days, time "
                + "FROM fall2014 "
                + "WHERE subject = 'CSCI' "
                + "ORDER BY course;";

        // Send a statement executing the query and saving the result set 
        rs = s.executeQuery(queryString);

        // print headings for output
        outfile.print("CRN" + "," + "Subject" + "," + "Course" + ","
                + "Section" + "," + "Days" + "," + "Time" + "," + "\n");

        // iterate through result set and print CRN, Subject, Course, Section, Days, time fields
        while (rs.next()) {
            outfile.print(rs.getString(1) + "," + rs.getString(2) + ","
                    + rs.getString(3) + "," + rs.getString(4) + ","
                    + rs.getString(5) + "," + rs.getString(6) + "\n");

        } // end while

        // close file
        outfile.close();

    } // end queryCSV()

    /* The following method performs an SQL query of the asked question:
     * Question: What 4 credit subject are available on Thursday? 
     * The parameter must be a Statement object with an established connection
     * to an SQL database.
     * Prins on the console machine 
     */
    public static void queryDesign(Statement s) throws Exception {
        System.out.println("Question:");
        System.out.println("What 4 credit subjects are available on Thursday? ");
        String queryString; // a String to hold an SQL query 
        ResultSet rs;       // the result set from an SQL query as a table

        // Create an SQL query as as String for this statement
        // this query returns all rows and all columns from the database 
        queryString = "SELECT subject, days, credits "
                + "FROM fall2014 "
                + "WHERE credits = '4' && days = 'TR'  "
                + "ORDER BY subject;";

        // Send a statement executing the query and saving the result set 
        rs = s.executeQuery(queryString);

        // print headings for output
        System.out.println("\n" + queryString + "\n");
        System.out.printf("%-15s%-15s%-15s%n", "Subject", "Days", "Credict #");
        System.out.println("*****************************************");

        // Iterate through the result set and print name, owner, and species attributes
        while (rs.next()) {
            System.out.printf("%-15s%-15s%-15s%n", rs.getString(1), rs.getString(2), rs.getString(3));
        }//end while

    } // end queryDesign()

} // end class JDBC
